In [1]:
!nvidia-smi

Mon Apr 12 05:47:28 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  !pip uninstall tb-nightly tensorboardX tensorboard
  !pip install tf-nightly
except Exception:
  pass

import tensorflow as tf

import os 
import datetime
import tensorflow_datasets as tfds

%load_ext tensorboard

Uninstalling tensorboard-2.4.1:
  Would remove:
    /usr/local/bin/tensorboard
    /usr/local/lib/python3.7/dist-packages/tensorboard-2.4.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorboard/*
Proceed (y/n)? y
  Successfully uninstalled tensorboard-2.4.1
     |████████████████████████████████| 455.4MB 36kB/s 
     |████████████████████████████████| 1.2MB 45.2MB/s 
     |████████████████████████████████| 4.0MB 10.8MB/s 
     |████████████████████████████████| 471kB 56.8MB/s 
     |████████████████████████████████| 4.0MB 52.7MB/s 
     |████████████████████████████████| 6.1MB 49.5MB/s 
     |████████████████████████████████| 3.9MB 54.1MB/s 
ERROR: tensorflow 2.4.1 requires tensorboard~=2.4, which is not installed.
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [5]:
import pkg_resources

for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins'):
  print(entry_point.dist)

tensorboard 2.4.1
tensorboard-plugin-wit 1.8.0


In [6]:
!ls -alrt /usr/local/lib/python3.6/dist-packages/tensorboard*

#!rm -r /usr/local/lib/python3.6/dist-packages/tensorboardcolab

ls: cannot access '/usr/local/lib/python3.6/dist-packages/tensorboard*': No such file or directory


In [7]:
print(tf.__version__)

2.4.1


In [8]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [9]:
dataset, info = tfds.load('amazon_us_reviews/Mobile_Electronics_v1_00', with_info=True)
train_dataset = dataset['train']

Shuffling and writing examples to /root/tensorflow_datasets/amazon_us_reviews/Mobile_Electronics_v1_00/0.1.0.incomplete0NWZ79/amazon_us_reviews-train.tfrecord


Dataset amazon_us_reviews downloaded and prepared to /root/tensorflow_datasets/amazon_us_reviews/Mobile_Electronics_v1_00/0.1.0. Subsequent calls will reuse this data.


In [10]:
info

tfds.core.DatasetInfo(
    name='amazon_us_reviews',
    version=0.1.0,
    description='Amazon Customer Reviews (a.k.a. Product Reviews) is one of Amazons iconic products. In a period of over two decades since the first review in 1995, millions of Amazon customers have contributed over a hundred million reviews to express opinions and describe their experiences regarding products on the Amazon.com website. This makes Amazon Customer Reviews a rich source of information for academic researchers in the fields of Natural Language Processing (NLP), Information Retrieval (IR), and Machine Learning (ML), amongst others. Accordingly, we are releasing this data to further research in multiple disciplines related to understanding customer product experiences. Specifically, this dataset was constructed to represent a sample of customer evaluations and opinions, variation in the perception of a product across geographical regions, and promotional intent or bias in reviews.

Over 130+ million cus

In [11]:
print(train_dataset)

<PrefetchDataset shapes: {data: {customer_id: (), helpful_votes: (), marketplace: (), product_category: (), product_id: (), product_parent: (), product_title: (), review_body: (), review_date: (), review_headline: (), review_id: (), star_rating: (), total_votes: (), verified_purchase: (), vine: ()}}, types: {data: {customer_id: tf.string, helpful_votes: tf.int32, marketplace: tf.string, product_category: tf.string, product_id: tf.string, product_parent: tf.string, product_title: tf.string, review_body: tf.string, review_date: tf.string, review_headline: tf.string, review_id: tf.string, star_rating: tf.int32, total_votes: tf.int32, verified_purchase: tf.int64, vine: tf.int64}}>


In [12]:
len(list(train_dataset))

104975

In [13]:
BUFFER_SIZE = 30000
BATCH_SIZE = 128

In [14]:
train_dataset = train_dataset.shuffle(BUFFER_SIZE, reshuffle_each_iteration=False)


In [15]:
for review in train_dataset.take(2):
  print(review)

{'data': {'customer_id': <tf.Tensor: shape=(), dtype=string, numpy=b'12903845'>, 'helpful_votes': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'marketplace': <tf.Tensor: shape=(), dtype=string, numpy=b'US'>, 'product_category': <tf.Tensor: shape=(), dtype=string, numpy=b'Mobile_Electronics'>, 'product_id': <tf.Tensor: shape=(), dtype=string, numpy=b'B00D1847NE'>, 'product_parent': <tf.Tensor: shape=(), dtype=string, numpy=b'274617424'>, 'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Teenage Mutant Ninja Turtles Boombox CD Player with Text Display, AM/FM Stereo Radio, Repeat Function'>, 'review_body': <tf.Tensor: shape=(), dtype=string, numpy=b'Bought this for my 4 & 5 yr old grandsons and they loved it.. Music played great and they had no problem figuring it out. The design is so colorful and we were all very satisfied'>, 'review_date': <tf.Tensor: shape=(), dtype=string, numpy=b'2015-01-08'>, 'review_headline': <tf.Tensor: shape=(), dtype=string, numpy=b'Awesome'>, 'revi

In [16]:
for review in train_dataset.take(2):
  review_text = review['data']
  print(review_text.get('review_body').numpy())
  print(review_text.get('star_rating'))
  print(tf.where(review_text.get('star_rating')>3,1,0).numpy())

b'Bought this for my 4 & 5 yr old grandsons and they loved it.. Music played great and they had no problem figuring it out. The design is so colorful and we were all very satisfied'
tf.Tensor(5, shape=(), dtype=int32)
1
b'My granddaughter liked these very much for her IPod we bought her for christmas. But the material is very flimsy and one is broken already.'
tf.Tensor(4, shape=(), dtype=int32)
1


In [20]:
tokenizer = tfds.deprecated.text.Tokenizer()

vocabulary_set = set()
for _, reviews in train_dataset.enumerate():
  review_text = reviews['data']
  review_tokens = tokenizer.tokenize(review_text.get('review_body').numpy())
  vocabulary_set.update(review_tokens)


vocab_size = len(vocabulary_set)
print(vocab_size)

73738


In [21]:
encoder = tfds.deprecated.text.TokenTextEncoder(vocabulary_set)

In [22]:
print(vocabulary_set)

{'ACU', 'XS', 'nonspeaker', 'kinter', 'instrustions', 'cantilevered', 'Linq', 'Jpeg', 'linguistics', 'pressings', 'DOC', 'FIT', '90v', 'ampage', 'Dashcams', 'defects', 'upsampled', '316', 'photosmart', 'RnB', 'indicado', '8', 'goning', 'LYING', 'handdle', '15pc', 'i931x', 'reluctance', 'WaveJamr', 'hopefuly', 'objectives', 'seesawing', 'Lover', 'Cubic', 'CONSCIENCE', 'RECOVERING', 'BLARING', 'dond', 'pom', 'Ahead', 'blurriness', 'Foxda', 'Linux', 'Mountaineer', 'ENTIRE', 'unceremoniously', 'advertsing', 'microsystem', 'BlueHarborOnline', 'sellers', 'Omething', 'Musician', 'WATCHING', 'THEY', 'whatnot', 'themselsves', 'iIunes', 'augment', 'RECHARGING', '500Mb', '12ish', 'streght', 'workstations', 'B00D05CCKS', 'monitoring', 'visceral', 'track', 'pleasently', 'tangled', 'incomodo', 'bestest', 'boarded', 'wingnut', 'Wrigley', 'tellng', 'CARD', 'amost', 'MTP', 'Xiaomi', 'corners', 'technics', '1024x768', 'singly', 'MlAh', 'low', 'REARS', 'pinion', 'fb2', 'Screens', 'recc', 'balasters', 'co

In [24]:
for review in train_dataset.take(5):
  review_text = review['data']
  print(review_text.get('review_body').numpy())
  encoded_example = encoder.encode(review_text.get('review_body').numpy())
  print(encoded_example)

b'Bought this for my 4 & 5 yr old grandsons and they loved it.. Music played great and they had no problem figuring it out. The design is so colorful and we were all very satisfied'
[41756, 26840, 10811, 55230, 49241, 10414, 16873, 44546, 46415, 55401, 1690, 18371, 50055, 39259, 56854, 73050, 55401, 1690, 42608, 62543, 47050, 72619, 50055, 5057, 48465, 57556, 19799, 38879, 17092, 55401, 34756, 4086, 71046, 31122, 29082]
b'My granddaughter liked these very much for her IPod we bought her for christmas. But the material is very flimsy and one is broken already.'
[47288, 42834, 70594, 6532, 31122, 8979, 10811, 11098, 47556, 34756, 62224, 11098, 10811, 5742, 43267, 44259, 1072, 19799, 31122, 41773, 55401, 68784, 19799, 32157, 70532]
b"These were an okay price and with buying a car charger for each of our cars, I bought 2 of these two packs, one for each car.  All the cables are fine.  I thought I bought them long enough to reach to the backseat, but I guess not.  That's not the fault of th

In [25]:
def encode(text_tensor, label_tensor):
  encoded_text = encoder.encode(text_tensor.numpy())
  label = tf.where(label_tensor>3,1,0)
  return encoded_text, label

In [27]:
def encode_map_fn(tensor):
  text = tensor['data'].get('review_body')
  label = tensor['data'].get('star_rating')

  encoded_text, label = tf.py_function(encode, 
                                       inp = [text, label],
                                       Tout=(tf.int64, tf.int32))
  

  encoded_text.set_shape([None])
  label.set_shape([])

  return encoded_text, label

In [28]:
ar_encoded_data = train_dataset.map(encode_map_fn)

In [29]:
for f0, f1 in ar_encoded_data.take(2):
  print(f0)
  print(f1)

tf.Tensor(
[41756 26840 10811 55230 49241 10414 16873 44546 46415 55401  1690 18371
 50055 39259 56854 73050 55401  1690 42608 62543 47050 72619 50055  5057
 48465 57556 19799 38879 17092 55401 34756  4086 71046 31122 29082], shape=(35,), dtype=int64)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(
[47288 42834 70594  6532 31122  8979 10811 11098 47556 34756 62224 11098
 10811  5742 43267 44259  1072 19799 31122 41773 55401 68784 19799 32157
 70532], shape=(25,), dtype=int64)
tf.Tensor(1, shape=(), dtype=int32)


In [30]:
TAKE_SIZE = 10000

train_data = ar_encoded_data.skip(TAKE_SIZE).shuffle(BUFFER_SIZE)
train_data = train_data.padded_batch(BATCH_SIZE)

test_data = ar_encoded_data.take(TAKE_SIZE)
test_data = test_data.padded_batch(BATCH_SIZE)

In [ ]:
vocab_size += 1

In [31]:
sample_text, sample_labels = next(iter(test_data))
sample_text[0], sample_labels[0]

(<tf.Tensor: shape=(565,), dtype=int64, numpy=
 array([41756, 26840, 10811, 55230, 49241, 10414, 16873, 44546, 46415,
        55401,  1690, 18371, 50055, 39259, 56854, 73050, 55401,  1690,
        42608, 62543, 47050, 72619, 50055,  5057, 48465, 57556, 19799,
        38879, 17092, 55401, 34756,  4086, 71046, 31122, 29082,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,  

In [43]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim = vocab_size+1, output_dim=128))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True)))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))
for units in [64, 64]:
  model.add(tf.keras.layers.Dense(units, activation='relu'))

model.add(tf.keras.layers.Dense(1))

In [44]:
!rm -r /tmp/logs

In [45]:
logpath = os.path.join('/tmp/logs', datetime.datetime.now().strftime("%Y-%m-%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logpath, histogram_freq=1)
checkpointer = tf.keras.callbacks.ModelCheckpoint(filepath='/tmp/sentiment_analysis.hdf5', verbose=1, save_best_only=True)

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
history = model.fit(train_data, epochs=4, validation_data=test_data, callbacks=[tensorboard_callback, checkpointer])


Epoch 1/4
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
742/742 [==============================] - ETA: 0s - loss: 0.4094 - accuracy: 0.8004WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x7ff46696e0e0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
742/742 [==============================] - 307s 366ms/step - loss: 0.4093 - accuracy: 0.8004 - val_loss: 0.3081 - val_accuracy: 0.8727

Epoch 00001: val_loss improved from inf to 0.30806, saving model to /tmp/sentiment_analysis.hdf5
Epoch 2/4
 87/742 [==>...........................] - ETA: 3:59 - loss: 0.2600 - accuracy: 0.8921

In [ ]:
model.save('/tmp/final_sentiment_analysis.hdf5')

In [ ]:
!ls -alrt /tmp/*.hdf5

In [ ]:
eval_loss, eval_acc = model.evaluate(test_data)
print('\nEval loss: {:.3f}, Eval accuracy {:.3f}'.format(eval_loss, eval_acc))

In [37]:
for f0,f1 in test_data.take(1):
  print(f1)
  print(model.predict(f0))

tf.Tensor(
[1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 0 0
 0 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0
 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1], shape=(128,), dtype=int32)
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[ 4.1489773 ]
 [ 1.9549581 ]
 [ 0.46064147]
 [ 3.5912416 ]
 [ 1.5708092 ]
 [ 4.5325413 ]
 [ 4.616793  ]
 [ 1.9759651 ]
 [ 1.6504129 ]
 [ 1.8931406 ]
 [ 4.1331215 ]
 [-2.9423594 ]
 [-1.0798817 ]
 [ 1.3315262 ]
 [ 2.336011  ]
 [ 2.847964  ]
 [ 3.8839371 ]
 [ 1.2578212 ]
 [ 2.5332124 ]
 [-0.3830264 ]
 [ 0.06609902]
 [-2.567543  ]
 [-0.61578876]
 [ 4.203502  ]
 [ 4.3085494 ]
 [-3.6701698 ]
 [ 0.27055177]
 [ 3.5690608 ]
 [-2.8314936 ]
 [ 3.2412853 ]
 [ 3.3376899 ]
 [ 2.5825415 ]
 [ 2.7971528 ]
 [ 4.0214043 ]
 [ 2.6849947 ]
 [ 2.3007588 ]
 [-2.2528858 ]
 [ 2.069706  ]
 [-4.853618  ]
 [ 3.9670646 ]
 [ 2.1093981 ]
 [-1.322921  ]
 [ 4.4961915 ]
 [ 0.6353197